[workspace]
members = [
    "cdumay_error",
    "cdumay_error_derive",
]
resolver = "2"

[patch.crates-io]
cdumay_error = { path = "cdumay_error" }

[workspace.dependencies]
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", default-features = false }
